import '../../home/domain/map_character_config.dart';
import 'store_category.dart';
import 'store_product.dart';

abstract final class StoreCatalog {
  static const int startCoins = 500;

  static final List<StoreProduct> products = [
    const StoreProduct(
      id: 'hammer_basic_3',
      category: StoreCategory.boosters,
      name: 'BASIC HAMMER',
      quantity: 3,
      price: 300,
      assetPath: 'assets/store/boosters/hammer-basic.webp',
      sortOrder: 10,
      grantType: StoreGrantType.tool,
      grantId: 'hammer_basic',
    ),
    const StoreProduct(
      id: 'hammer_stone_3',
      category: StoreCategory.boosters,
      name: 'STONE HAMMER',
      quantity: 3,
      price: 500,
      assetPath: 'assets/store/boosters/hammer-stone.webp',
      sortOrder: 11,
      grantType: StoreGrantType.tool,
      grantId: 'hammer_stone',
    ),
    const StoreProduct(
      id: 'hammer_cross_3',
      category: StoreCategory.boosters,
      name: 'CROSS HAMMER',
      quantity: 3,
      price: 600,
      assetPath: 'assets/store/boosters/hammer-cross.webp',
      sortOrder: 12,
      grantType: StoreGrantType.tool,
      grantId: 'hammer_cross',
    ),
    const StoreProduct(
      id: 'hammer_harvest_3',
      category: StoreCategory.boosters,
      name: 'HARVEST HAMMER',
      quantity: 3,
      price: 800,
      assetPath: 'assets/store/boosters/hammer-harvest.webp',
      sortOrder: 13,
      grantType: StoreGrantType.tool,
      grantId: 'hammer_harvest',
    ),
    const StoreProduct(
      id: 'hammer_spread_3',
      category: StoreCategory.boosters,
      name: 'SPREAD HAMMER',
      quantity: 3,
      price: 1000,
      assetPath: 'assets/store/boosters/hammer-spread.webp',
      sortOrder: 14,
      grantType: StoreGrantType.tool,
      grantId: 'hammer_spread',
    ),
    const StoreProduct(
      id: 'hammer_color_3',
      category: StoreCategory.boosters,
      name: 'COLOR HAMMER',
      quantity: 3,
      price: 1500,
      assetPath: 'assets/store/boosters/hammer-color.webp',
      sortOrder: 15,
      grantType: StoreGrantType.tool,
      grantId: 'hammer_color',
    ),
    const StoreProduct(
      id: 'swap_pair_3',
      category: StoreCategory.boosters,
      name: 'SWAP PAIR',
      quantity: 3,
      price: 300,
      assetPath: 'assets/store/boosters/icon-booster-swap.webp',
      sortOrder: 20,
      grantType: StoreGrantType.tool,
      grantId: 'swap_pair',
    ),
    const StoreProduct(
      id: 'swap_shuffle_3',
      category: StoreCategory.boosters,
      name: 'SHUFFLE',
      quantity: 3,
      price: 600,
      assetPath: 'assets/store/boosters/icon-booster-swap.webp',
      sortOrder: 21,
      grantType: StoreGrantType.tool,
      grantId: 'swap_shuffle',
    ),
    const StoreProduct(
      id: 'chest_gold_1',
      category: StoreCategory.chests,
      name: 'GOLD CHEST',
      quantity: 1,
      price: 1500,
      assetPath: 'assets/store/chests/icon-chest.webp',
      sortOrder: 10,
      grantType: StoreGrantType.chest,
      grantId: 'chest_gold',
    ),
    const StoreProduct(
      id: 'chest_item_1',
      category: StoreCategory.chests,
      name: 'ITEM CHEST',
      quantity: 1,
      price: 1800,
      assetPath: 'assets/store/chests/chest-item.webp',
      sortOrder: 11,
      grantType: StoreGrantType.chest,
      grantId: 'chest_item',
    ),
    const StoreProduct(
      id: 'chest_fragment_1',
      category: StoreCategory.chests,
      name: 'FRAGMENT CHEST',
      quantity: 1,
      price: 3000,
      assetPath: 'assets/store/chests/chest-fragment.webp',
      sortOrder: 12,
      grantType: StoreGrantType.chest,
      grantId: 'chest_fragment',
    ),
    const StoreProduct(
      id: 'chest_mixed_1',
      category: StoreCategory.chests,
      name: 'MIXED CHEST',
      quantity: 1,
      price: 2400,
      assetPath: 'assets/store/chests/chest-mixed.webp',
      sortOrder: 13,
      grantType: StoreGrantType.chest,
      grantId: 'chest_mixed',
    ),
    const StoreProduct(
      id: 'chest_special_1',
      category: StoreCategory.chests,
      name: 'SPECIAL CHEST',
      quantity: 1,
      price: 12000,
      assetPath: 'assets/store/chests/chest-special.webp',
      sortOrder: 14,
      grantType: StoreGrantType.chest,
      grantId: 'chest_special',
    ),
    const StoreProduct(
      id: 'coins_s',
      category: StoreCategory.coins,
      name: 'COIN PACK S',
      quantity: 500,
      price: .99,
      currency: 'USD',
      assetPath: 'assets/store/coins/icon-coin.webp',
      sortOrder: 10,
      grantType: StoreGrantType.coins,
      grantId: 'coins_s',
    ),
    const StoreProduct(
      id: 'coins_m',
      category: StoreCategory.coins,
      name: 'COIN PACK M',
      quantity: 1700,
      price: 2.99,
      currency: 'USD',
      assetPath: 'assets/store/coins/icon-coin.webp',
      sortOrder: 20,
      grantType: StoreGrantType.coins,
      grantId: 'coins_m',
    ),
    const StoreProduct(
      id: 'coins_l',
      category: StoreCategory.coins,
      name: 'COIN PACK L',
      quantity: 6000,
      price: 7.99,
      currency: 'USD',
      assetPath: 'assets/store/coins/icon-coin.webp',
      sortOrder: 30,
      grantType: StoreGrantType.coins,
      grantId: 'coins_l',
    ),
    ...MapCharacterConfig.characters
        .skip(1)
        .map(
          (character) => StoreProduct(
            id: 'dino_${character.id}',
            category: StoreCategory.dino,
            name: character.name.toUpperCase(),
            quantity: 1,
            price: 6000,
            assetPath: character.asset,
            sortOrder: 10 + MapCharacterConfig.characters.indexOf(character),
            grantType: StoreGrantType.dino,
            grantId: character.id,
            isUnique: true,
          ),
        ),
    const StoreProduct(
      id: 'pet_triceratops',
      category: StoreCategory.pet,
      name: 'TRICERATOPS',
      quantity: 1,
      price: 1200,
      assetPath: 'assets/store/pets/green-triceratops.webp',
      sortOrder: 5,
      grantType: StoreGrantType.pet,
      grantId: 'triceratops',
      isUnique: true,
    ),
    const StoreProduct(
      id: 'pet_trex',
      category: StoreCategory.pet,
      name: 'T-REX',
      quantity: 1,
      price: 1500,
      assetPath: 'assets/store/pets/t-rex.webp',
      sortOrder: 10,
      grantType: StoreGrantType.pet,
      grantId: 'trex',
      isUnique: true,
    ),
    const StoreProduct(
      id: 'pet_pteranodon',
      category: StoreCategory.pet,
      name: 'PTERANODON',
      quantity: 1,
      price: 2000,
      assetPath: 'assets/store/pets/pteranodon.webp',
      sortOrder: 20,
      grantType: StoreGrantType.pet,
      grantId: 'pteranodon',
      isUnique: true,
    ),
    const StoreProduct(
      id: 'food_1_pack',
      category: StoreCategory.pet,
      name: 'BERRY SNACK',
      quantity: 3,
      price: 15,
      assetPath: 'assets/store/pets/fruit.webp',
      sortOrder: 100,
      grantType: StoreGrantType.food,
      grantId: 'food_1',
    ),
    const StoreProduct(
      id: 'food_2_pack',
      category: StoreCategory.pet,
      name: 'MEAT BOWL',
      quantity: 3,
      price: 75,
      assetPath: 'assets/store/pets/hamburger.webp',
      sortOrder: 101,
      grantType: StoreGrantType.food,
      grantId: 'food_2',
    ),
    const StoreProduct(
      id: 'food_3_pack',
      category: StoreCategory.pet,
      name: 'GIANT STEAK',
      quantity: 3,
      price: 135,
      assetPath: 'assets/store/pets/pork-chop.webp',
      sortOrder: 102,
      grantType: StoreGrantType.food,
      grantId: 'food_3',
    ),
    const StoreProduct(
      id: 'food_4_pack',
      category: StoreCategory.pet,
      name: 'DINO FEAST',
      quantity: 3,
      price: 90,
      assetPath: 'assets/store/pets/chicken-drumstick.webp',
      sortOrder: 103,
      grantType: StoreGrantType.food,
      grantId: 'food_4',
    ),
  ];

  static List<StoreProduct> byCategory(StoreCategory category) =>
      products.where((item) => item.category == category).toList()
        ..sort((a, b) => a.sortOrder.compareTo(b.sortOrder));
}
